---
title: "Visualizations"
author: "Phil"
date: "1/22/2018"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(ggjoy)
source('models.R')

data_dir <- 'Evolving-Voter/Code/data/'
files <- list.files(data_dir, full.names = T) 
files <- files[grepl('.process', files)]
```

```{r}
read_files <- function(mode){
    df <- files[grepl(paste0('mode_', mode), files)] %>% 
        map(fread) %>% 
        bind_rows()
  
    method <- ifelse(mode == 0, 'random', 'same')
    df %>% 
        mutate(mode = method)
}

df <- c(0,1) %>% 
    map(read_files) %>% 
    bind_rows() %>% 
    tbl_df()
```

```{r}
df <- df %>% 
    filter(step > 2000000,
           N01_prev > 0) %>% 
    mutate(c = (N00 + 2*N01 + N11)/ (N0 + N1),
           x = 2*N01 / (N00 + 2*N01 + N11),
           dN = N01 - N01_prev,
           u = N1/(N0 + N1),
           mode = as.character(mode)) %>% 
    filter(c >= 4)  
```


# basic plot, add approximations on top of this

```{r}

plot_df <- df %>% 
    filter(abs(u - .5) < .05) %>% 
    # filter(log2(lambda) < -8) %>% 
    mutate(u = round(u/5, 2)*5,
           u = pmin(u, 1-u)) %>% 
    group_by(alpha, lambda, c, mode) %>% 
    summarise(x = mean(x),
              n = n()) 

approx <- function(a, c, l, p){
    return((-1 + c-a*(c-1+2*p) + l*(1 + c + a*c))/(2*c*(1 - a + l + a*l)))
}


approx_df <- expand.grid(c = c(4, 6, 8, 20),
                         alpha = 0:200*(.005),
                         lambda = plot_df$lambda %>% unique) %>% 
    mutate(approx = pmap_dbl(.l = list(alpha, c, lambda), approx, p = .5),
           approx = pmax(approx, 0)) %>% 
    mutate(log_lambda = round(log2(lambda))) %>% 
    filter(log_lambda %% 2 == 0) %>% 
    mutate(log_lambda = factor(log_lambda, levels = -(3:10)))

plot_df %>% 
    mutate(log_lambda = round(log2(lambda))) %>% 
    filter(log_lambda %% 2 == 0) %>% 
    mutate(log_lambda = factor(log_lambda, levels = -(3:10))) %>% 
    filter(c >= 4, mode == 'random', (round((alpha*100)) %% 5) == 0) %>% 
    mutate(p = ifelse(mode == 'random', .5,1),
           approx = pmap_dbl(.l = list(alpha, c, lambda, p), approx),
           approx = pmax(approx, 0)) %>% 
    ggplot() + 
    aes(x = alpha, y = x, fill = log_lambda) + 
    geom_line(aes(y = approx, color = log_lambda, group = lambda), data = approx_df) + 
    geom_point(pch = 21) + 
    facet_wrap(~c, nrow = 2) +
    # theme_dark() +
    scale_color_brewer(palette = 'Dark2') + 
    scale_fill_brewer(palette = 'Dark2') + 
    scale_x_continuous(breaks = (0:10)*.1) + 
    theme_bw() + 
    guides(fill = guide_legend(title = expression(log[2]~lambda)),
           color = FALSE) + 
    xlab(expression(alpha)) + 
    ylab(expression(x)) 

ggsave('../fig/approx_informal.pdf', width = 8, height = 7)

```

# Full set of data points

```{r}

transition_df <- expand.grid(lambda = df$lambda %>% unique(),
                             c = 1:30, 
                             mode = df$mode %>% unique(),
                             stringsAsFactors = F) %>% 
    tbl_df() %>% 
    mutate(transition_approx = pmap_dbl(.l = list(lambda, .5, c, mode), 
                                        .f = transition)) 


plot_df <- df %>% 
    filter(abs(u - .5) < .05) %>% 
    # filter(log2(lambda) < -8) %>% 
    mutate(u = round(u/5, 2)*5,
           u = pmin(u, 1-u)) %>% 
    group_by(alpha, lambda, c, mode) %>% 
    summarise(x = mean(x),
              n = n()) 

transition_sub <- transition_df %>% 
    filter(c %in% plot_df$c)


plot_df %>% 
    
    # filter(c >= 4) %>% 
    ggplot() + 
    aes(x = alpha, y = x, fill = lambda) + 
    geom_point(pch = 21) + 
    facet_grid(mode~c) + 
    viridis::scale_fill_viridis() + 
    theme_dark() + 
    geom_vline(aes(xintercept = transition_approx,
                   color = lambda), data = transition_sub) + 
    viridis::scale_color_viridis()
```

```{r}
approx_df <- expand.grid(lambda = df$lambda %>% unique(),
                         alpha = (0:100)*.01,
                         u = .5,
                         c = c(4, 6, 8, 20), 
                         mode = df$mode %>% unique(),
                         stringsAsFactors = F) %>% 
    tbl_df() %>% 
    nest(-lambda, -u, -c, -mode) %>% 
    mutate(approxer = pmap(.l = list(lambda, u, c, mode), 
                            .f = linearized_approx),
           approx = map2(data, approxer, function(x,y) y(x$alpha)),
           data = map2(data, approx, function(x,y) cbind(alpha=x, approx=y))) %>% 
    select(-approxer, -approx) %>% 
    unnest()
# %>% 
#     filter(lambda == min(lambda))


plot_df %>% 
    ungroup() %>%
    # filter(round(alpha*100) %% 10 == 0) %>% 
    # filter(lambda == min(lambda)) %>% 
    ggplot() +
    aes(x = alpha, y = x, fill = lambda, group = lambda) + 
    geom_point(pch = 21) + 
    facet_grid(mode~c) + 
    viridis::scale_fill_viridis() + 
    theme_dark() + 
    viridis::scale_color_viridis() + 
    geom_line(aes(y = approx, color = lambda), data = approx_df)

    

```

# $lambda = 0$ case
```{r}
approx_df <- expand.grid(lambda = df$lambda %>% unique(),
                         alpha = (0:100)*.01,
                         u = .5,
                         c = c(4, 6, 8, 20), 
                         mode = df$mode %>% unique(),
                         stringsAsFactors = F) %>% 
    tbl_df() %>% 
    nest(-lambda, -u, -c, -mode) %>% 
    mutate(approxer = pmap(.l = list(lambda, u, c, mode), 
                            .f = linearized_approx),
           approx = map2(data, approxer, function(x,y) y(x$alpha)),
           data = map2(data, approx, function(x,y) cbind(alpha=x, approx=y))) %>% 
    select(-approxer, -approx) %>% 
    unnest() %>%
    filter(lambda == min(lambda))

plot_df %>% 
    ungroup() %>%
    filter(round(alpha*100) %% 5 == 0) %>%
    filter(lambda == min(lambda)) %>%
    ggplot() +
    aes(x = alpha, y = x, fill = factor(c), group = c) + 
    geom_point(pch = 21) + 
    facet_grid(~mode) + 
    scale_color_brewer(palette = 'Dark2') + 
    scale_fill_brewer(palette = 'Dark2') + 
    theme_bw() +
    geom_line(aes(y = approx, color = factor(c)), data = approx_df) + 
    guides(color = FALSE,
           fill = guide_legend(title = expression(c))) + 
    xlab(expression(alpha)) + 
    scale_y_continuous(limits = c(0, .5))

ggsave('../fig/full_approx_lambda_0.pdf', width = 6, height = 2.5)

```


# phase transition with varying $\alpha$.

```{r}

sub_df <- plot_df %>% 
    filter(c == 4) %>% 
    mutate(log_lambda = round(log2(lambda))) %>% 
    filter(log_lambda %in% -c(3, 4, 5, 6)) %>% 
    mutate(log_lambda = factor(log_lambda, 
                               levels = log_lambda %>% unique() %>% sort(decreasing = F))) %>% 
    filter(round(alpha*100) %% 2 == 0)

sub_transition <- transition_df %>% 
    mutate(log_lambda = round(log2(lambda))) %>% 
    filter(c %in% sub_df$c, 
           log_lambda %in% sub_df$log_lambda) %>% 
        mutate(log_lambda = factor(log_lambda, 
                               levels = sub_df$log_lambda %>% unique() %>% sort(decreasing = F)))

sub_df %>% 
    ggplot() + 
    aes(x = alpha, y = x, fill = log_lambda) + 
    facet_grid(~mode) + 
    theme_bw() + 
    geom_vline(aes(xintercept = transition_approx, color = log_lambda), data = sub_transition, size = 1) +
    geom_point(pch = 21) + 
    xlab(expression(alpha)) + 
    ylab(expression(x)) + 
    scale_color_brewer(palette = 'Set2') + 
    scale_fill_brewer(palette = 'Set2') + 
    guides(fill = guide_legend(title = expression(log[2]~lambda)),
           color = F)

ggsave('../fig/phase_transition_detailed.pdf', width = 7, height = 3)

```



# detailed transition plot

```{r}

transition_df <- expand.grid(lambda = df$lambda %>% unique(),
                             c = 1:30, 
                             mode = df$mode %>% unique(),
                             stringsAsFactors = F) %>% 
    tbl_df() %>% 
    mutate(transition_approx = pmap_dbl(.l = list(lambda, .5, c, mode), 
                                        .f = transition)) 
    
sub_transition <- transition_df %>% 
    filter(lambda == min(lambda))
    
plot_df %>% 
    ungroup() %>% 
    filter(lambda == min(lambda)) %>% 
    ggplot() + 
    aes(x = alpha, y = c) + 
    geom_joy(aes(height = x, group = c), stat = 'identity') +
    facet_wrap(~mode) + 
    geom_line(aes(x = transition_approx), 
              data= sub_transition, 
              color = 'firebrick') + 
    theme_bw() + 
    scale_x_reverse() + 
    scale_y_continuous(breaks = c(4, 6, 8, 20), limits = c(1, 30)) + 
    xlab(expression(alpha)) + 
    ylab(expression(c))

ggsave('../fig/transition_joy.pdf', width = 6, height = 3)
```

# Arch visualization

```{r}

df %>% 
    mutate(u = round(u, 2)) %>% 
    filter(abs((alpha*100) %% 5) <.00001) %>% 
    group_by(alpha, u, mode, c) %>% 
    summarise(x = mean(x),
              n = n()) %>% 
    ggplot() + 
    aes(x = u, y = x, fill = alpha, color = alpha, alpha = n) + 
    facet_grid(mode ~ c) + 
    geom_point(pch = 21) + 
    viridis::scale_color_viridis() + 
    viridis::scale_fill_viridis() + 
    theme_dark()

```


# Voter impact vs. x -- roughly linear. Add an approximation on top of this. 

```{r}

df %>% 
    filter(action == 0,
           step > 2000000,
           abs(u - .5) < .02,
           lambda == min(lambda)) %>% 
    mutate(x = round(x, 2)) %>% 
    group_by(c, mode,  lambda, x) %>% 
    summarise(dN = mean(dN)) %>% 
    ungroup() %>% 
    nest(-c, -lambda, -mode) %>% 
    mutate(f = pmap(.l = list(lambda, .5, c, mode), .f = linearized_voter),
           preds = map2(f, data, ~.x(.y$x)),
           data = map2(data, preds, cbind)) %>% 
    unnest(data) %>% 
    rename(pred = `.y[[i]]`) %>% 
    ggplot() + 
    aes(x = x) + 
    facet_grid(mode~c, scales = 'free_y') + 
    geom_line(aes(y = pred/c, group = c), color = 'firebrick', size = 1) + 
    theme_bw() + 
    geom_smooth(aes(y = dN/c), se = F, color = 'black') + 
    geom_point(aes(y = dN/c), pch = 21) + 
    ylab(expression(V/c))

ggsave('../fig/V_term_empirical.pdf', width = 8, height = 3.5)


```




